version: '3.1'
services:
#  loadbalancer:
#      build: ./load-balancer
#      links:
#          - web
#      ports:
#          - '80:80'  
  web:
    build:
      context: .
      args:
        - WWW_UID=${UID:-1000}
    ports:
 #     - 8080:80
      - 80:80 
    environment:
    - TOTO=42  
    volumes:
      - "./web/:/var/www/html/web"
    restart: always
